!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  blue_h_max: 31
  blue_h_min: 11
  blue_s_max: 255
  blue_s_min: 204
  blue_v_max: 200
  blue_v_min: 45
  green_h_max: 63
  green_h_min: 46
  green_s_max: 192
  green_s_min: 84
  green_v_max: 206
  green_v_min: 66
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      blue_h_max: 31
      blue_h_min: 11
      blue_s_max: 255
      blue_s_min: 204
      blue_v_max: 200
      blue_v_min: 45
      green_h_max: 63
      green_h_min: 46
      green_s_max: 192
      green_s_min: 84
      green_v_max: 206
      green_v_min: 66
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      red_h_max: 131
      red_h_min: 119
      red_s_max: 255
      red_s_min: 119
      red_v_max: 255
      red_v_min: 108
      state: true
      type: ''
      yellow_h_max: 94
      yellow_h_min: 80
      yellow_s_max: 254
      yellow_s_min: 64
      yellow_v_max: 255
      yellow_v_min: 115
    state: []
  red_h_max: 131
  red_h_min: 119
  red_s_max: 255
  red_s_min: 119
  red_v_max: 255
  red_v_min: 108
  yellow_h_max: 94
  yellow_h_min: 80
  yellow_s_max: 254
  yellow_s_min: 64
  yellow_v_max: 255
  yellow_v_min: 115
state: []
